---
ID: "e11d2813-1f89-4be5-93b9-c6e313878bcc"
Parent: "9bcf014c-b5d2-4493-8826-da06cd02ebfb"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/PlaySites/Services/Default Services Variant/$name/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8f537d42-cd60-4cc5-bcc5-5aed3cd780a7"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ffec05c4-c3d9-4e7f-b664-244d06910590"
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ffec05c4-c3d9-4e7f-b664-244d06910590"
